name: btc_forecasting_env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.3.3
  - matplotlib=3.9.2
  - scikit-learn=1.7.1
  - pytorch=2.2.2
  - pip
